### ISSUE TITLE
After installation it does not start

### ISSUE THREAD

**Issue by ylian89** [flathub/com.github.tenderowl.norka#1]
Hello, 
I tried the application on my pc with Elementary OS but both installing it from Flathub and reposity does not start in any way. I see the icon appear in the dock and after a few seconds it closes.

**Comment by amka** [comment]
@ylian89 this issue is confirmed and will be fixed in a few days. Thank you for your report.

**Comment by amka** [comment]
Should be fixed in [1.0.1](https://github.com/TenderOwl/Norka/releases/tag/1.0.1). Please try to update.
